### PR TITLE
Copyright updated with current year

### PR DESCRIPTION
**Pull request by Rattone**

### CODE REVIEW

**Comment by Omranic** [comment]
Thanks, please submit to the `develop` branch (you can edit from GitHub interface)

**Comment by Rattone** [comment]
> Thanks, please submit to the `develop` branch (you can edit from GitHub interface)

Forgive me but I have read it now. Sorry for the inconvenience, I noticed the problem after seeing the merge in develop.
Hope that's not a big problem, thanks for the tip

**Comment by Omranic** [comment]
No worries, thanks anyway for all the help 🙌 Keep it up!

**Comment by Omranic** [comment]
We follow [Git-Flow](http://nvie.com/posts/a-successful-git-branching-model/), that's why all PRs must go to `develop` instead of `master`. Here more details in case it's helpful 😉 

- http://nvie.com/posts/a-successful-git-branching-model/
- https://github.com/rinvex/laravel-statistics/blob/master/CONTRIBUTING.md

**Comment by Rattone** [comment]
> We follow [Git-Flow](http://nvie.com/posts/a-successful-git-branching-model/), that's why all PRs must go to `develop` instead of `master`. Here more details in case it's helpful 😉
> 
> * http://nvie.com/posts/a-successful-git-branching-model/
> * https://github.com/rinvex/laravel-statistics/blob/master/CONTRIBUTING.md

Yes, I could have imagined it (and read it 😅), these are my first contributions for a public repo, I took the opportunity to practice. Thank you very much for your spirit and your excellent work 💯

**Comment by Omranic** [comment]
Sure thing, all PRs are now merged, good start 👏
You're welcome to contribute anytime!

**Pull request merged**
